In [248]:
import pandas as pd
import numpy as np
import plotly.express as px
df = pd.read_csv("spam.csv",encoding='latin1')
df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

DATA PREPROCESSING

In [249]:
df.drop(['Unnamed: 2','Unnamed: 3','Unnamed: 4'],axis='columns',inplace=True)

In [250]:
df

v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [251]:
df.rename({'v1':'spam_or_not','v2':'language'},axis='columns',inplace=True)

In [252]:
df

spam_or_not                                           language
0            ham  Go until jurong point, crazy.. Available only ...
1            ham                      Ok lar... Joking wif u oni...
2           spam  Free entry in 2 a wkly comp to win FA Cup fina...
3            ham  U dun say so early hor... U c already then say...
4            ham  Nah I don't think he goes to usf, he lives aro...
...          ...                                                ...
5567        spam  This is the 2nd time we have tried 2 contact u...
5568         ham              Will Ì_ b going to esplanade fr home?
5569         ham  Pity, * was in mood for that. So...any other s...
5570         ham  The guy did some bitching but I acted like i'd...
5571         ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

Encoding Categorical value

In [253]:
from sklearn.preprocessing import LabelEncoder
le =  LabelEncoder()
df['spam_or_not_encoded'] = le.fit_transform(df['spam_or_not'])

In [254]:
df

spam_or_not                                           language  \
0            ham  Go until jurong point, crazy.. Available only ...   
1            ham                      Ok lar... Joking wif u oni...   
2           spam  Free entry in 2 a wkly comp to win FA Cup fina...   
3            ham  U dun say so early hor... U c already then say...   
4            ham  Nah I don't think he goes to usf, he lives aro...   
...          ...                                                ...   
5567        spam  This is the 2nd time we have tried 2 contact u...   
5568         ham              Will Ì_ b going to esplanade fr home?   
5569         ham  Pity, * was in mood for that. So...any other s...   
5570         ham  The guy did some bitching but I acted like i'd...   
5571         ham                         Rofl. Its true to its name   

      spam_or_not_encoded  
0                       0  
1                       0  
2                       1  
3                       0  
4                       0  
...                   ...  
5567                    1  
5568                    0  
5569                    0  
5570                    0  
5571                    0  

[5572 rows x 3 columns]

Deleting the Spam or not column

In [255]:
df.drop(['spam_or_not'],axis='columns',inplace=True)

In [256]:
df

language  spam_or_not_encoded
0     Go until jurong point, crazy.. Available only ...                    0
1                         Ok lar... Joking wif u oni...                    0
2     Free entry in 2 a wkly comp to win FA Cup fina...                    1
3     U dun say so early hor... U c already then say...                    0
4     Nah I don't think he goes to usf, he lives aro...                    0
...                                                 ...                  ...
5567  This is the 2nd time we have tried 2 contact u...                    1
5568              Will Ì_ b going to esplanade fr home?                    0
5569  Pity, * was in mood for that. So...any other s...                    0
5570  The guy did some bitching but I acted like i'd...                    0
5571                         Rofl. Its true to its name                    0

[5572 rows x 2 columns]

Data Visualization

In [257]:
spam = (df['spam_or_not_encoded'] == 1).sum()
ham = (df['spam_or_not_encoded'] == 0).sum()
fig = px.bar(x = ['spam = 1','ham = 0'],y = [spam,ham],title="Spam and Ham Mails",)
fig.update_xaxes(title_text="Spam & Ham")
fig.update_yaxes(title_text="Counts")

Data set contains the ham mail in excess amount 

In [258]:
df['lan_len'] = df['language'].apply(len)
fig = px.histogram(df,'lan_len',color='spam_or_not_encoded')
fig.show()

From the histogram the ham mail have typical length of 0 -100
Whereas the spam have the length between 120 - 170


Cleaning the message 

In [259]:
df.drop(['lan_len'],axis='columns',inplace=True)
df.tail()

language  spam_or_not_encoded
5567  This is the 2nd time we have tried 2 contact u...                    1
5568              Will Ì_ b going to esplanade fr home?                    0
5569  Pity, * was in mood for that. So...any other s...                    0
5570  The guy did some bitching but I acted like i'd...                    0
5571                         Rofl. Its true to its name                    0

In [260]:
import re
import nltk  #help in removing stocks words i.e and ,the,a,or
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer #change different word into one word which have same meaning
corpus = [] #contains the cleaned data
for i in range(0,5572):
    review=re.sub('[^a-zA-Z]', ' ', df['language'][i])#remove special characters from text
    review=review.lower()   #convert to lower case
    review=review.split()
    ps = PorterStemmer()
    all_stop = stopwords.words('english')
    all_stop.remove('not')
    review = [ps.stem(word) for word in review if not word in set(all_stop)] 
    review = ' '.join(review)
    corpus.append(review)

[nltk_data] Error loading stopwords: <urlopen error [WinError 10060] A
[nltk_data]     connection attempt failed because the connected party
[nltk_data]     did not properly respond after a period of time, or
[nltk_data]     established connection failed because connected host
[nltk_data]     has failed to respond>


In [261]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother not like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank brea

Creating Bag of Words to make message to machine understandable language

In [262]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
x= cv.fit_transform(corpus).toarray()
y= df.iloc[:,-1].values

import joblib
joblib.dump(cv, 'count_vectorizer.pkl')

['count_vectorizer.pkl']

In [263]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [264]:
y

array([0, 0, 1, ..., 0, 0, 0])

Splitting the data into train and test set

In [265]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [266]:
x_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [267]:
y_train

array([0, 0, 0, ..., 0, 0, 0])

Gaussian Naive Bayes

In [268]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(x_train,y_train)

GaussianNB()

In [269]:
y_pred = gnb.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [270]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
mat1 = confusion_matrix(y_test,y_pred)
score1 = accuracy_score(y_test,y_pred)
rep1 = classification_report(y_test,y_pred)
print("Confusion Matrix: ")
print(mat1)
print()
print("Accuracy Score: ",score1 * 100)
print()
print("Report: ")
print(rep1)

Confusion Matrix: 
[[822 127]
 [ 24 142]]

Accuracy Score:  86.45739910313901

Report: 
              precision    recall  f1-score   support

           0       0.97      0.87      0.92       949
           1       0.53      0.86      0.65       166

    accuracy                           0.86      1115
   macro avg       0.75      0.86      0.78      1115
weighted avg       0.91      0.86      0.88      1115



Mulitple Naive Bayes

In [271]:
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()
mnb.fit(x_train, y_train)

MultinomialNB()

In [272]:
mnb_pred = mnb.predict(x_test)
mnb_pred

array([0, 0, 0, ..., 0, 0, 0])

In [273]:
mat2 = confusion_matrix(y_test,mnb_pred)
score2 = accuracy_score(y_test,mnb_pred)
rep2 = classification_report(y_test,mnb_pred)
print("Confusion Matrix: ")
print(mat2)
print()
print("Accuracy Score: ",score2 * 100)
print()
print("Report: ")
print(rep2)

Confusion Matrix: 
[[934  15]
 [  6 160]]

Accuracy Score:  98.11659192825111

Report: 
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       949
           1       0.91      0.96      0.94       166

    accuracy                           0.98      1115
   macro avg       0.95      0.97      0.96      1115
weighted avg       0.98      0.98      0.98      1115



Logistic Regression

In [274]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(x_train,y_train)


LogisticRegression()

In [275]:
lr_pred = lr.predict(x_test)
lr_pred

array([0, 0, 0, ..., 0, 0, 0])

In [276]:
mat3 = confusion_matrix(y_test,lr_pred)
score3 = accuracy_score(y_test,lr_pred)
rep3 = classification_report(y_test,lr_pred)
print("Confusion Matrix: ")
print(mat3)
print()
print("Accuracy Score: ",score3 * 100)
print()
print("Report: ")
print(rep3)

Confusion Matrix: 
[[949   0]
 [ 25 141]]

Accuracy Score:  97.75784753363229

Report: 
              precision    recall  f1-score   support

           0       0.97      1.00      0.99       949
           1       1.00      0.85      0.92       166

    accuracy                           0.98      1115
   macro avg       0.99      0.92      0.95      1115
weighted avg       0.98      0.98      0.98      1115



SVM

In [277]:
from sklearn.svm import SVC
svm =SVC(kernel='rbf')
svm.fit(x_train,y_train)

SVC()

In [278]:
svm_pred = svm.predict(x_test)

In [279]:
mat4 = confusion_matrix(y_test,svm_pred)
score4 = accuracy_score(y_test,svm_pred)
rep4 = classification_report(y_test,svm_pred)
print("Confusion Matrix: ")
print(mat4)
print()
print("Accuracy Score: ",score4 * 100)
print()
print("Report: ")
print(rep4)

Confusion Matrix: 
[[949   0]
 [ 28 138]]

Accuracy Score:  97.48878923766816

Report: 
              precision    recall  f1-score   support

           0       0.97      1.00      0.99       949
           1       1.00      0.83      0.91       166

    accuracy                           0.97      1115
   macro avg       0.99      0.92      0.95      1115
weighted avg       0.98      0.97      0.97      1115



Out of all Model Multiple Naive Bayes has the Grestest Accuracy of 98%

In [280]:
loaded_cv = joblib.load('count_vectorizer.pkl')
input_mail = ["I'm gonna be home soon and i don't want to talk about this stuff anymore tonight, k? I've cried enough today."]
x= loaded_cv.transform(input_mail).toarray()
newpred = mnb.predict(x)


In [281]:
newpred

array([0])